import type { Metadata } from "next";
import "./globals.css";
import "./tiptap.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { fonts } from "../lib/fonts";
import { Providers } from "../providers/chakra";
import ReactQueryClient from "../providers/react-query";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <ReactQueryClient>
          <Providers>{children}</Providers>
        </ReactQueryClient>
      </body>
    </html>
  );
}
